[package]
name = "codecrafters-sqlite"
version = "0.1.0"
authors = []
edition = "2021"
rust-version = "1.80"

[dependencies]
anyhow = "*"
bytes = "*"
thiserror = "*"
nom = "*"
clap = { version = "*", features = ["derive"] }
