[package]
name = "RQlite"
version = "0.1.0"
authors = []
edition = "2024"

[dependencies]
anyhow = "*"
bytes = "*"
thiserror = "*"
nom = "*"
clap = { version = "*", features = ["derive"] }
axum = "*"
tokio = { version = "*", features = ["full"] }
assert_cmd = "*"
predicates = "*"